version: '2.2'
services:
  mariadb:
    image: mariadb:10.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=demo_sh

  hatstall:
    image: grimoirelab/hatstall:latest
    environment:
      - DATABASE_DIR=/db/
      - ADMIN_USER=admin
      - ADMIN_PASS=admin
    ports:
      - 5602:80
    links:
      - mariadb
    depends_on:
      - mariadb
    volumes:
      - ../config/default-grimoirelab-settings/apache-hatstall.conf:/home/grimoirelab/apache-hatstall.conf
      - ../config/default-grimoirelab-settings/shdb.cfg:/home/grimoirelab/shdb.cfg

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ELASTIC_USERNAME=elastic"
      - "ELASTIC_PASSWORD=123456"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - ../config/elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
      - ../config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
      - ../config/elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
      - ../config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - esnet
  kibiter:
    image: guoqiangqi/kibiter:community-v6.8.6-3
    container_name: kibiter
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    volumes:
      - ../config/kibana.yml:/opt/kibana/config/kibana.yml
    networks:
      - esnet

  grimoirelab:
    image: guoqiangqi/grimoirelab:v1.1
    container_name: grimoirelab
    depends_on:
      - elasticsearch
    volumes:
      - ../config/default-grimoirelab-settings/:/root/repos/grimoirelab/default-grimoirelab-settings/
      - ../config/default-grimoirelab-settings/panels/json/:/root/repos/sigils/panels/json
    networks:
      - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:
    driver: bridge
